# Uncomment this line to define a global platform for your project
 platform :ios, '7.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Cloud_APT' do
    pod 'AFNetworking', '~> 3.0.4'
    pod 'MJRefresh', '~> 3.1.0'
    pod 'SDWebImage', '~> 3.7.5'
end

target 'Cloud_APTTests' do

end

target 'Cloud_APTUITests' do

end

