# Uncomment the next line to define a global platform for your project
  platform :ios, '9.0'

target 'WalkReporter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WalkReporter

  target 'WalkReporterTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'AFNetworking', '~> 3.1.0'
    pod 'SnapKit', '~> 3.0.2'
    pod 'MBProgressHUD', '~> 1.0.0'
  end

  target 'WalkReporterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
