# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'WalkReporter' do
    pod 'AFNetworking', '~> 3.0.4'
    pod 'SnapKit', '~> 0.19.1'
    pod 'MBProgressHUD', '~> 0.9.2'
end

target 'WalkReporterTests' do

end

target 'WalkReporterUITests' do

end

